"""empty message

Revision ID: 9075e9532216
Revises: 
Create Date: 2019-06-23 22:33:18.328178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9075e9532216'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escritor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('livro', sa.String(length=255), nullable=True),
    sa.Column('escritor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escritor_id'], ['escritor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    op.drop_table('escritor')
    # ### end Alembic commands ###
